language: node_js
node_js:
  - "10"
cache:
  directories:
    - "node_modules"
install:
    - npm i
    - (cd src/services/dashboard/web; npm i)
script: npm run build-pkg
deploy:
  provider: releases
  api_key:
    secure: YOUR_API_KEY_ENCRYPTED
  file:
    - "bin/chatplug-linux"
    - "bin/chatplug-macos"
    - "bin/chatplug-win.exe"
  skip_cleanup: true
  on:
    tags: true
