export const LOAD_INSTANCES = 'loadInstances'
export const LOAD_MODULES = 'loadModules'
export const SET_INSTANCES = 'setInstances'
export const SET_MODULES = 'setModules'
export const LOAD_INSTANCE_CONFIG_SCHEMA = 'loadInstanceConfigSchema'
export const SET_INSTANCE_CONFIG_SCHEMA = 'setInstanceConfigSchema'
